---
- hosts: k8s-clients
  tasks:
    - name: Check /kthw folder
      file:
        path: /kthw
        state: directory
    - name: Synchronize /kthw with required files
      copy:
        src: "files/sync/"
        dest: "/kthw"
    - name: Generate Certificate Authority in /kthw
      shell: "cfssl gencert -initca ca-csr.json | cfssljson -bare ca"
      args:
        chdir: "/kthw"
        creates: "ca-key.pem"
